
{
"name" : "Transferencias internas",
"version" : "1.0",
"author" : "Carlos López Mite",
"website" : "http://www.blaze-otp.com",
"category" : "Inventory",
"depends" : [
    'base',
    'uom',
    'product',
    'stock',
    'stock_account',
    'odoo_utils',
    'generic_stock',
    'generic_stock_account',
],
"description": """Standard Process""",
"data": [
    'data/module_category_data.xml',
    'security/groups.xml',
    'security/ir.model.access.csv',
    'data/sequence_data.xml',
    #'data/notification_data.xml',
    'views/menu_root.xml',
    'views/stock_transfers_reports.xml',
    'reports/transfer_requisition_report_analisis_view.xml',
    #'reports/report_transfer_requisition.xml',
    #'reports/report_transfer_requisition_list.xml',
    'wizard/wizard_report_transfer_requisition_view.xml',
    'wizard/wizard_approved_transfer_requisition_view.xml',
    'wizard/wizard_received_transfer_requisition_view.xml',
    'views/transfer_requisition_view.xml',
    'views/stock_config_view.xml',
],
"installable": True,
}
