
from . import mrp_workorder
from . import stock_production_lot
from . import mrp_production
from . import stock_production_lot_serial
from . import stock_move_line
from . import stock_picking
from . import stock_location
from . import potential_lot
from . import mrp_workcenter
from . import quality_analysis
from . import product_category
from . import dried_oven
from . import unpelled_dried
from . import oven_use
from . import product_product
from . import stock_traceability
from . import dried_unpelled_history
from . import manufacturing_pallet
from . import res_partner
