# -*- coding: utf-8 -*-

from . import account_invoice
from . import account_invoice_references
from . import custom_economic_activity
from . import custom_fired
from . import custom_invoice
from . import dte_type
from . import res_company
from . import res_partner
from . import rut_helper
from . import stock_location
from . import stock_picking
from . import custom_settlement
from . import custom_holidays
from . import hr_payslip
from . import hr_leave
from . import hr_payslip_worked_days
from . import hr_leave_type
from . import hr_contract
from . import wizard
from . import custom_data
from . import account_invoice_xlsx
from . import account_invoice_line
from . import custom_invoice_observations
from . import custom_receiving_country_dte
from . import custom_sale_method
from . import custom_type_transport
from . import custom_export_clause
from . import custom_package_type
from . import custom_package
from . import custom_uom
from . import hr_salary_rule
from . import sale_order
from . import res_country
from . import res_currency
from . import custom_orders_in_invoice