{
    "name": "Mejoras en Proceso de Compras",
    'version': '1.0.0.2',
    "author": "Carlos Lopez Mite",
    "website": "https://blaze-otp.com",
    'category': 'Purchases',
    "description": """Mejoras en Proceso de Compras""",
    'depends': [
        'purchase',
        'odoo_utils',
        'generic_account',
    ],
    'data': [
        'data/module_category_data.xml',
        'data/system_data_init.xml',
        'security/groups.xml',
        'security/ir.model.access.csv',
        'views/menu_root.xml',
        'views/purchase_report_view.xml',
        'views/purchase_view.xml',
        'reports/report_purchase_order.xml',
        'views/portal_templates.xml',
        'views/generic_purchase_assets.xml',
    ],
    'installable': True,
    'auto_install': True,
}
