{
    "name" : "Reportes genericos para Almacen/Logistica",
    'version': '1.0.0.0',
    "author" : "Carlos López Mite",
    "website": "https://blaze-otp.com",
    "category" : "Warehouse",
    "description": """Reportes genericos para Almacen/Logistica""",
    "depends" : [
        'base',
        'product',
        'stock',
        'odoo_utils',
        'generic_stock',
        'email_template_qweb',
        'stock_picking_show_backorder',
        'uom',
    ],
    "data": [
        'security/groups.xml',
        'security/ir.model.access.csv',
        'data/mail_template_view.xml',
        'data/mail_template.xml',
        'data/cron_jobs.xml',
        'views/generic_stock_reports.xml',
        'reports/report_kardex_individual.xml',
        'reports/report_kardex_all.xml',
        'views/report_stock_inventory_view.xml',
        'views/report_product_stock_view.xml',
        'wizard/wizard_kardex_individual_view.xml',
        'wizard/wizard_kardex_all_view.xml',
    ],
    "installable": True,
    "auto_install": True,
}
