{
    'name': 'Mejoras en Proceso de Ventas',
    'version': '1.0.0.0',
    'category': 'Sales',
    'description': """Mejoras en Proceso de Ventas""",
    'author': 'Carlos Lopez Mite(celm1990@hotmail.com)',
    'depends': [
        'sale',
        'sales_team',
        'odoo_utils',
        'generic_account',
    ],
    'data': [
        'data/module_category_data.xml',
        'data/system_data_init.xml',
        'security/groups.xml',
        'security/ir.model.access.csv',
        'views/menu_root.xml',
        'views/crm_team_dashboard_view.xml',
        'views/crm_team_view.xml',
        'views/sale_order_view.xml',
        'views/sale_report_view.xml',
        'views/partner_view.xml',
        'views/product_view.xml',
    ],
    'installable': True,
    'auto_install': True,
}
