#colores y valores por defecto
from .css_variables import *
#estilos basicos
styles = {
'table': 'width: 100%;',
'col_1': 'width: 8.33333333%;',
'col_2': 'width: 16.66666667%;',
'col_3': 'width: 25%;',
'col_4': 'width: 33.33333333%;',
'col_5': 'width: 41.66666667%;',
'col_6': 'width: 50%;',
'col_7': 'width: 58.33333333%;',
'col_8': 'width: 66.66666667%;',
'col_9': 'width: 75%;',
'col_10': 'width: 83.33333333%;',
'col_11': 'width: 91.66666667%;',
'col_12': 'width: 100%;',
'text_right': 'text-align:right;',
'text_center': 'text-align:center;',
'text_left': 'text-align:left;',
'line_height': 'line-height:1.42857;',
'vertical_align': 'vertical-align:top;',
#combinacion de estilos
'header_padding': 'padding: 10px;',
'row_padding': 'padding: 8px;',
'row_bordered': '%s%s%s' % (border_color, border_style, border_width),
#colores de temas
'bg_alpha': 'color:%(color)s;background-color: %(bg_color)s;' % {'color': color_white, 'bg_color': bg_color_alpha},
'bg_beta': 'color:%(color)s;background-color: %(bg_color)s;' % {'color': color_white, 'bg_color': bg_color_beta},
'bg_gamma': 'color:%(color)s;background-color: %(bg_color)s;' % {'color': color_white, 'bg_color': bg_color_gamma},
'bg_delta': 'color:%(color)s;background-color: %(bg_color)s;' % {'color': color_white, 'bg_color': bg_color_delta},
'bg_epsilon': 'color:%(color)s;background-color: %(bg_color)s;' % {'color': color_white, 'bg_color': bg_color_epsilon},
'bg_white': 'color:%(color)s;background-color: %(bg_color)s;' % {'color': color_black, 'bg_color': bg_color_white},
'bg_gray_lighter': 'color:%(color)s;background-color: %(bg_color)s;' % {'color': color_black, 'bg_color': bg_color_gray_lighter},
'bg_gray_light': 'color:%(color)s;background-color: %(bg_color)s;' % {'color': color_white, 'bg_color': bg_color_gray_light},
'bg_gray': 'color:%(color)s;background-color: %(bg_color)s;' % {'color': color_white, 'bg_color': bg_color_gray},
'bg_gray_dark': 'color:%(color)s;background-color: %(bg_color)s;' % {'color': color_white, 'bg_color': bg_color_gray_dark},
'bg_gray_darker': 'color:%(color)s;background-color: %(bg_color)s;' % {'color': color_white, 'bg_color': bg_color_gray_darker},
'bg_black': 'color:%(color)s;background-color: %(bg_color)s;' % {'color': color_white, 'bg_color': bg_color_black},
'bg_primary': 'color:%(color)s;background-color: %(bg_color)s;' % {'color': color_white, 'bg_color': bg_color_primary},
'bg_success': 'color:%(color)s;background-color: %(bg_color)s;' % {'color': color_black, 'bg_color': bg_color_success},
'bg_info': 'color:%(color)s;background-color: %(bg_color)s;' % {'color': color_black, 'bg_color': bg_color_info},
'bg_warning': 'color:%(color)s;background-color: %(bg_color)s;' % {'color': color_black, 'bg_color': bg_color_warning},
'bg_danger': 'color:%(color)s;background-color: %(bg_color)s;' % {'color': color_black, 'bg_color': bg_color_danger},
}